[workspace]
members = ["edgestore", "edgestore-cli", "edgestore-repl", "edgestore-tokio"]
resolver = "2"

[workspace.package]
version = "1.0.5"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gleicon/edgestore"
homepage = "https://github.com/gleicon/edgestore"
readme = "README.md"
