[package]
name = "edgestore-repl"
version = "0.1.0"
edition = "2021"

[dependencies]
edgestore = { path = "../edgestore" }
ureq = { version = "2", features = [] }
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
blake3 = "1"

[dev-dependencies]
tempfile = "3"
