[package]
name = "edgestore-cli"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "EdgeStore CLI - Administrative tool for managing EdgeStore databases"
keywords = ["cli", "kv", "database", "edgestore"]
categories = ["database-implementations", "command-line-utilities"]

[[bin]]
name = "edgestore-cli"
path = "src/main.rs"

[dependencies]
edgestore = { path = "../edgestore", version = "1.1.2" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
fs2 = "0.4"
